version: '3'
services:
  node1:
    image: raft-node
    environment:
      - NODE_ID=node1
      - NODE_ADDR=node1:50051
      - GRPC_PORT=50051
      - PEER_NODES={"node2":"node2:50052","node3":"node3:50053"}
    networks:
      raft-net:
        aliases:
          - node1
    ports:
      - "50051:50051"

  node2:
    image: raft-node
    environment:
      - NODE_ID=node2
      - NODE_ADDR=node2:50052
      - GRPC_PORT=50052
      - PEER_NODES={"node1":"node1:50051","node3":"node3:50053"}
    networks:
      raft-net:
        aliases:
          - node2
    ports:
      - "50052:50051"

  node3:
    image: raft-node
    environment:
      - NODE_ID=node3
      - NODE_ADDR=node3:50053
      - GRPC_PORT=50053
      - PEER_NODES={"node1":"node1:50051","node2":"node2:50052"}
    networks:
      raft-net:
        aliases:
          - node3
    ports:
      - "50053:50051"

networks:
  raft-net:
    driver: bridge
